-- MySQL Script generated by MySQL Workbench
-- 12/12/16 00:03:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TPays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TPays` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TPays` (
  `nomPays` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`nomPays`))
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `nomPays_UNIQUE` ON `mydb`.`TPays` (`nomPays` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TRegion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TRegion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TRegion` (
  `noReg` INT NOT NULL,
  `nomRegion` VARCHAR(45) NULL,
  `nomPays` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`noReg`),
  CONSTRAINT `constraint_fk_TRegion_nomPays`
  FOREIGN KEY (`nomPays`)
  REFERENCES `mydb`.`TPays` (`nomPays`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `noReg_UNIQUE` ON `mydb`.`TRegion` (`noReg` ASC);

CREATE UNIQUE INDEX `nomPays_UNIQUE` ON `mydb`.`TRegion` (`nomPays` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TDepartement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TDepartement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TDepartement` (
  `noDep` INT NOT NULL,
  `nomDep` VARCHAR(45) NOT NULL,
  `noReg` INT NOT NULL,
  PRIMARY KEY (`noDep`),
  CONSTRAINT `constraint_fk_TDepartement_noRegion`
  FOREIGN KEY (`noReg`)
  REFERENCES `mydb`.`TRegion` (`noReg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `noDep_UNIQUE` ON `mydb`.`TDepartement` (`noDep` ASC);

CREATE UNIQUE INDEX `nomPays_UNIQUE` ON `mydb`.`TDepartement` (`noReg` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TEvenement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TEvenement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TEvenement` (
  `date` DATETIME NOT NULL,
  `noDep` INT NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `desc` VARCHAR(200) NULL,
  PRIMARY KEY (`date`, `noDep`),
  CONSTRAINT `constraint_fk_TEvenement_noDep`
  FOREIGN KEY (`noDep`)
  REFERENCES `mydb`.`TDepartement` (`noDep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_XY_UNIQUE` ON `mydb`.`TEvenement` (`noDep` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TDonneesMeteo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TDonneesMeteo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TDonneesMeteo` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `noDep` INT NOT NULL,
  `date` DATE NOT NULL,
  `heure` VARCHAR(8) NOT NULL,
  `temperature` DECIMAL(3,1) NULL,
  `vitesseVent` DECIMAL(5,2) NULL,
  `directionVent` VARCHAR(5) NULL,
  `pression` DECIMAL(6,2) NULL,
  `neige` DECIMAL(5,2) NULL,
  `precipitation` DECIMAL(5,2) NULL,
  `humidite` DECIMAL(5,2) NULL,
  PRIMARY KEY (`id`,`noDep`),
  CONSTRAINT `constraint_fk_TdonneesMeteo_noDep`
  FOREIGN KEY (`noDep`)
  REFERENCES `mydb`.`TDepartement` (`noDep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_XY_UNIQUE` ON `mydb`.`TDonneesMeteo` (`id` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TVille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TVille` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TVille` (
  `nomVille` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`nomVille`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TDepVille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TDepVille` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TDepVille` (
  `noDep` INT NOT NULL,
  `nomVille` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`noDep`, `nomVille`),
  CONSTRAINT `constraint_fk_TDepVille_nomVille`
  FOREIGN KEY (`nomVille`)
  REFERENCES `mydb`.`TVille` (`nomVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `constraint_fk_TDepVille_noDep`
  FOREIGN KEY (`noDep`)
  REFERENCES `mydb`.`TDepartement` (`noDep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE INDEX `constraint_fk_TCoordVille_nomVille_idx` ON `mydb`.`TDepVille` (`nomVille` ASC);

CREATE UNIQUE INDEX `id_XY_UNIQUE` ON `mydb`.`TDepVille` (`noDep` ASC);

CREATE UNIQUE INDEX `nomVille_UNIQUE` ON `mydb`.`TDepVille` (`nomVille` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TUtilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TUtilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TUtilisateur` (
  `idUtilisateur` VARCHAR(15) NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(20) NOT NULL,
  `sexe` VARCHAR(1) NOT NULL,
  `mail` VARCHAR(150) NULL,
  `adresse` VARCHAR(200) NULL,
  `motDePasse` VARCHAR(500) NOT NULL,
  `inscritAlerte` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idUtilisateur`))
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `idUtilisateur_UNIQUE` ON `mydb`.`TUtilisateur` (`idUtilisateur` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TVilleUtilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TVilleUtilisateur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TVilleUtilisateur` (
  `idUtilisateur` VARCHAR(15) NOT NULL,
  `nomVille` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idUtilisateur`, `nomVille`),
  CONSTRAINT `constraint_fk_TVilleUtilisateur_nomVille`
  FOREIGN KEY (`nomVille`)
  REFERENCES `mydb`.`TVille` (`nomVille`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `constraint_fk_TVilleUtilisateur_idUtilisateur`
  FOREIGN KEY (`idUtilisateur`)
  REFERENCES `mydb`.`TUtilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `idUtilisateur_UNIQUE` ON `mydb`.`TVilleUtilisateur` (`idUtilisateur` ASC);

CREATE INDEX `constraint_fk_TVilleUtilisateur_nomVille_idx` ON `mydb`.`TVilleUtilisateur` (`nomVille` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TLog` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TLog` (
  `date` DATE NOT NULL,
  `idUtilisateur` VARCHAR(15) NOT NULL,
  `desc` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`date`, `idUtilisateur`),
  CONSTRAINT `constraint_fk_TLog_idUtilisateur`
  FOREIGN KEY (`idUtilisateur`)
  REFERENCES `mydb`.`TUtilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `idUtilisateur_UNIQUE` ON `mydb`.`TLog` (`idUtilisateur` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

drop table if exists `mydb`.`temp`;

create table if not exists `mydb`.`temp`(
  `id` MEDIUMINT(9) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `jour` VARCHAR(30) NOT NULL,
  `heure` VARCHAR(30) NOT NULL,
  `temp` decimal(3,1) NULL
);

LOAD DATA INFILE 'C://Users//Charly//Documents//temperature_pdd//temp_pdd2009.csv'
into table temp
fields terminated by ','
lines terminated by '\n'
IGNORE 1 lines;

LOAD DATA INFILE 'C://Users//Charly//Documents//temperature_pdd//temp_pdd2010.csv'
into table temp
fields terminated by ','
lines terminated by '\n'
IGNORE 1 lines;

DROP PROCEDURE IF EXISTS transferer;
DELIMITER |
CREATE PROCEDURE transferer()

  BEGIN
    DECLARE v_date datetime;
    DECLARE v_heure VARCHAR(8);
    DECLARE v_data decimal(3,1);
    declare fin TINYINT DEFAULT 0;
    DECLARE cur CURSOR
    FOR SELECT str_to_date(jour,'%Y-%m-%d'),heure,temp
        from mydb.temp;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET fin=1;

    open cur;
    loop_cur: LOOP
      FETCH cur INTO v_date,v_heure,v_data;
      IF fin=1 THEN
        LEAVE loop_cur;
      END IF;
      insert into mydb.tdonneesmeteo (noDep,date,heure,temperature) values(63,v_date,v_heure,v_data);
    END LOOP;
    close cur;
  END|
DELIMITER ;

CALL transferer();

drop table if exists temp;
drop procedure if exists transferer;
